name: QA

on:
  push:
    branches:
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build project
        uses: actions/setup-node@v2
        with:
          node-version: "16"
        env:
          VITE_APP_BASE_URL: https://mesaims-dev.herokuapp.com
      - run: npx pnpm i
      - run: npx pnpm build

      - name: Deploy to staging environment
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_QA_ID }}
        with:
          args: deploy --dir=dist --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'