name: Staging

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: create env file
        run: |
          touch .env
          echo VITE_APP_BASE_URL =https://mesaims-stg.herokuapp.com >> .env
      - uses: actions/checkout@v2
      - name: Build project
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npx pnpm i
      - run: npx pnpm build
        env:
          VITE_APP_BASE_URL: https://mesaims-stg.herokuapp.com

      - name: Deploy to staging environment
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STAG_ID }}
        with:
          args: deploy --dir=dist --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'